name: Format
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun
      - run: bun install --frozen-lockfile
      - run: bunx prettier . --check
